(in-package :mh-dex-web)

(def-widget weapon-page ((active-page :attribute))
  (:app-page ((name "weapon-page")
              (active-page active-page))
             (:table ((class "mdl-data-table" "mdl-js-data-table" "mdl-shadow-2dp"))
                     (:thead ()
                             (:tr ()
                                  (:th ((class "mdl-data-table__cell--non-numeric"))
                                       "Name")
                                  (:th () "Damage")))
                     (:tbody ()
                             (:tr ()
                                  (:td ((class "mdl-data-table__cell--non-numeric"))
                                       "Power Blade")
                                  (:td () 123))
                             (:tr ()
                                  (:td ((class "mdl-data-table__cell--non-numeric"))
                                       "Power Blade II")
                                  (:td () 334))))))
